In [193]:
import glob
import cv2
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D,Dense,MaxPool2D,Flatten,Dropout
from keras.preprocessing import image

In [213]:
cv_img =[]
for img in glob.glob("C:\\Users\Sahil\Desktop\data\helmet/*"):
    n= cv2.imread(img)
    resized=cv2.resize(n,(50,50))
    cv_img.append(resized)
x=np.asarray(cv_img)

In [214]:
lis=os.listdir("C:\\Users\Sahil\Desktop\data\helmet")
y=[]
for i in range(len(lis)):
    if lis[i].startswith("h"):                #helmet=0
        y.append(0)                           
    else:
        y.append(1)
y=np.asarray(y)

In [218]:
model=Sequential()
model.add(Conv2D(50,strides=1, padding='SAME',kernel_size=5))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(50,strides=1, padding='SAME',kernel_size=5,))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

In [219]:
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])
model.fit(x,y,epochs=30)

Epoch 1/30
191/191 [==============================] - 7s 34ms/step - loss: 7.5986 - acc: 0.5183
Epoch 2/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 3/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 4/30
191/191 [==============================] - 3s 18ms/step - loss: 8.1799 - acc: 0.4869
Epoch 5/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 6/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 7/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 8/30
191/191 [==============================] - 3s 18ms/step - loss: 8.1799 - acc: 0.4869
Epoch 9/30
191/191 [==============================] - 3s 16ms/step - loss: 8.1799 - acc: 0.4869
Epoch 10/30
191/191 [==============================] - 3s 17ms/step - loss: 8.1799 - acc: 0.4869
Epoch 11/30
191/191 [==================

In [220]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_64 (Conv2D)           (None, 50, 50, 50)        3800      
_________________________________________________________________
max_pooling2d_60 (MaxPooling (None, 25, 25, 50)        0         
_________________________________________________________________
conv2d_65 (Conv2D)           (None, 25, 25, 50)        62550     
_________________________________________________________________
max_pooling2d_61 (MaxPooling (None, 12, 12, 50)        0         
_________________________________________________________________
flatten_28 (Flatten)         (None, 7200)              0         
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 7201      
Total params: 73,551
Trainable params: 73,551
Non-trainable params: 0
_________________________________________________________________


In [231]:
test=[]
img=cv2.imread("C:\\Users\Sahil\Desktop\o.png")
b  resized=cv2.resize(img,(50,50))
test.append(resized)
test=np.asarray(test)
model.predict(test)

[[[244 241 230]
  [244 242 230]
  [245 241 230]
  ...
  [240 239 224]
  [240 239 224]
  [239 238 224]]

 [[244 244 232]
  [244 243 231]
  [244 243 231]
  ...
  [240 239 224]
  [239 238 223]
  [239 238 224]]

 [[244 243 233]
  [244 243 233]
  [244 243 233]
  ...
  [240 239 224]
  [240 238 224]
  [239 238 224]]

 ...

 [[211 205 175]
  [212 205 175]
  [215 204 176]
  ...
  [219 212 192]
  [219 212 192]
  [219 212 192]]

 [[209 205 175]
  [211 205 175]
  [214 203 175]
  ...
  [219 212 192]
  [219 212 192]
  [219 212 192]]

 [[208 204 174]
  [212 204 175]
  [212 203 175]
  ...
  [220 213 193]
  [219 212 192]
  [219 212 192]]]


array([[1.]], dtype=float32)