In [1]:
import glob
import cv2
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D,Dense,MaxPool2D,Flatten,Dropout
from keras.preprocessing import image

Using TensorFlow backend.


In [7]:
cv_img =[]
for img in glob.glob("*/*"):
    n= cv2.imread(img)
    resized=cv2.resize(n,(50,50))
    cv_img.append(resized)
x=np.asarray(cv_img)
x

array([[[[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94]],

        [[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94]],

        [[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94]],

        ...,

        [[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 44,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94]],

        [[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94]],

        [[ 45,  66,  94],
         [ 45,  66,  94],
         [ 45,  66,  94],
         ...,
         [ 45,  66,  94],
        

In [11]:
lis=os.listdir("helmet/")
y=[]
for i in range(len(lis)):
    if lis[i].startswith("h"):                #helmet=0
        y.append(0)                           
    else:
        y.append(1)
y=np.asarray(y)
y,x.shape

(array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1]), (191, 50, 50, 3))

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [20]:
model=Sequential()
model.add(Conv2D(50, padding='SAME',kernel_size=(5,5),input_shape=(50,50,3)))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(50, padding='SAME',kernel_size=5,))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

In [21]:
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])
model.fit(x_train,y_train,epochs=30,validation_data=(x_test,y_test))

Train on 143 samples, validate on 48 samples
Epoch 1/30
143/143 [==============================] - 1s 9ms/step - loss: 119.7335 - accuracy: 0.5245 - val_loss: 7.4733 - val_accuracy: 0.7708
Epoch 2/30
143/143 [==============================] - 1s 6ms/step - loss: 10.1834 - accuracy: 0.7133 - val_loss: 19.8247 - val_accuracy: 0.5833
Epoch 3/30
143/143 [==============================] - 1s 6ms/step - loss: 12.6967 - accuracy: 0.7343 - val_loss: 1.4152 - val_accuracy: 0.8750
Epoch 4/30
143/143 [==============================] - 1s 7ms/step - loss: 6.1902 - accuracy: 0.8322 - val_loss: 6.6528 - val_accuracy: 0.8125
Epoch 5/30
143/143 [==============================] - 1s 7ms/step - loss: 1.0936 - accuracy: 0.9510 - val_loss: 0.7632 - val_accuracy: 0.9792
Epoch 6/30
143/143 [==============================] - 1s 6ms/step - loss: 0.3252 - accuracy: 0.9720 - val_loss: 3.1904 - val_accuracy: 0.9167
Epoch 7/30
143/143 [==============================] - 1s 7ms/step - loss: 1.6492 - accuracy: 0.944

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 50, 50, 50)        3800      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 50)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 50)        62550     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 50)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 7200)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 7201      
Total params: 73,551
Trainable params: 73,551
Non-trainable params: 0
__________________________________________________

In [39]:
test=[]
img=cv2.imread("/Users/sahilsagar/Desktop/down.jpg")
resized=cv2.resize(img,(50,50))
test.append(resized)
test=np.asarray(test)
model.predict_classes(test)

array([[1]], dtype=int32)

In [42]:
model.save("helmet.h5")